#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  3 10:10:11 2022

@author: abp19
"""

import numpy as np
import matplotlib.pyplot as plt
import random
box=1000
def randomwalk2D(n):
    # [0, 0, 0, ... ,0]
    x = 100+np.zeros(n)
    y = 100+np.zeros(n)
    directions = ["UP", "DOWN", "LEFT", "RIGHT"]
    for i in range(1, n):
        # Pick a direction at random
        step = random.choice(directions)
        
        # Move the object according to the direction
        if step == "RIGHT":
            if x[i-1]<box:
                x[i] = x[i - 1] + 10
                y[i] = y[i - 1]
        elif step == "LEFT":
            if x[i-1]>0:
                x[i] = x[i - 1] - 10
                y[i] = y[i - 1]
        elif step == "UP":
            if y[i-1]<box:
                x[i] = x[i - 1]
                y[i] = y[i - 1] + 10
        elif step == "DOWN":
            if y[i-1]>0:
                x[i] = x[i - 1]
                y[i] = y[i - 1] - 10
    
    # Return all the x and y positions of the object
    return x, y


x_data, y_data = randomwalk2D(10000)
plt.title("2D Random Walk in Python")
plt.plot(x_data, y_data)
plt.xlim([-5, 1000])
plt.ylim([-5, 1000])
plt.show()